import type { Metadata } from "next";
import { Roboto_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { User } from "lucide-react";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: '800'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.className} antialiased`}
      >
        <nav className="p-5 flex flex-row justufy-between bg-gradient-to-b from-[#110117] to-[#120e1b]">
        <div className="flex">
          <div className="w-10 h-10 text-3xl">x{/*<Image src={""} alt={""} />*/}</div>
          <h1 className="font-[Poppins] text-5xl">FlashCards</h1>
        </div>
        <div className="ml-auto flex justify-center items-center">
          <User size={30} href="/abc"/>
        </div>
      </nav>
        {children}
      </body>
    </html>
  );
}
